export const data = {
  portfolios: [
    {
      id: 1,
      href: "https://nuhcar.com/",
      imageName: "img/19.webp",
      title: "AutoNuh",
    },
    {
      id: 14,
      href: "http://blasto.az/",
      imageName: "img/blasto.webp",
      title: "Blasto",
    },
    {
      id: 14,
      href: "https://drillsupport.com/",
      imageName: "img/drillsupport.webp",
      title: "Drill Support",
    },
    {
      id: 15,
      href: "https://az-dag-meden.com/",
      imageName: "img/azdag.webp",
      title: "Azer Dag Madan",
    },
    {
      id: 2,
      href: "https://googlec.vercel.app/",
      imageName: "img/2.webp",
      title: "Google Clone",
    },
    {
      id: 3,
      href: "https://covid19trackerapp.vercel.app/",
      imageName: "img/1.webp",
      title: "Covid19 tracker with VueJs",
    },
    {
      id: 4,
      href: "https://covid19trackerreact.vercel.app/",
      imageName: "img/1.webp",
      title: "Covid19 tracker with ReactJs",
    },
    {
      id: 5,
      href: "https://shakingtree.vercel.app/",
      imageName: "img/18.webp",
      title: "Shaking Tree",
    },
    {
      id: 6,
      href: "https://vuetodoapp.vercel.app/",
      imageName: "img/23.webp",
      title: "VueJs Todo app",
    },
    {
      id: 7,
      href: "https://sasocket.vercel.app/",
      imageName: "img/25.webp",
      title: "MERN Socket.io chat",
    },
    {
      id: 8,
      href: "https://sachat.vercel.app/",
      imageName: "img/25.webp",
      title: "MERN Pusher chat",
    },
    {
      id: 9,
      href: "https://brainhouseanticafe.herokuapp.com/",
      imageName: "img/20.webp",
      title: "Brain House",
    },
    {
      id: 10,
      href: "https://alizade.herokuapp.com/",
      imageName: "img/21.webp",
      title: "Portfolio with React",
    },
    {
      id: 11,
      href: "https://sabitalizade.herokuapp.com/",
      imageName: "img/22.webp",
      title: "Blog with Php",
    },
    {
      id: 12,
      href: "https://asyatodo.netlify.app/",
      imageName: "img/23.webp",
      title: "Todo with React",
    },
    {
      id: 13,
      href: "https://asya.netlify.app/",
      imageName: "img/24.webp",
      title: "Chat with React",
    },
  ],
};
