name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
#       run: ls
      run: docker-compose -f prod.yml up -d --build
