name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f prod.yml up -d --build
